services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 3000
    volumes:
      - ./:/app
      - /app/node_modules
      - adote-pets-db:/app/prisma     
    restart: always
    networks:
      - adote-pets-network

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 5555
    volumes:
      - ./:/app
      - /app/node_modules
      - adote-pets-db:/app/prisma      
    command: npx prisma studio --port 5555 --hostname 0.0.0.0
    depends_on:
      - app
    restart: always
    networks:
      - adote-pets-network

volumes:
  adote-pets-db:

networks:
  adote-pets-network:
    driver: bridge
